{{if .Values.createGcpArtifactorySecret}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-artifactory
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: gsm
  target:
    name: gcp-artifactory
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{.Values.dockerconfig | toJson | quote}}
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: gcp-artifactory-read-credentials
{{end}}
