{{if or .Values.createGcpArtifactorySecret .Values.secrets }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: gsm
spec:
  provider:
    gcpsm:
      projectID: {{.Values.secretsProjectId | quote}}
{{end}}
