{{- range $secretName, $secretData := .Values.secrets }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: gsm
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
  {{ range $secretKey, $gsmSecretId := $secretData }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $gsmSecretId }}
  {{ end }}
---
{{- end }}
