{{- range $saName, $saOptions := .Values.serviceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName | quote }}
  annotations:
    {{if $saOptions.googleServiceAccountEmail}}
    iam.gke.io/gcp-service-account: {{ $saOptions.googleServiceAccountEmail | quote }}
    {{end}}
{{if $.Values.createGcpArtifactorySecret}}
imagePullSecrets:
  - name: gcp-artifactory
{{end}}
---
{{- end }}
